### ISSUE TITLE
Test that an actor cannot Abort with a system exit code

### ISSUE THREAD

**Issue by anorth** [filecoin-project/test-vectors#15]
Test that if an actor calls Abortf with an ExitCode within the range [0, 15] the runtime should abort with SysErrorIllegalActor.

Test also that a negative value also results in SysErrorIllegalActor

**Comment by raulk** [comment]
Since all built-in actors are presumed to behave correctly and not violate this rule, I suspect we will need to implement a custom actor type and register it via `vm.Invoker#Register(code cid.Cid, actorLogic Invokee, stateType interface{})`.

Assigning to me for now, because this requires further investigation, and likely batching all these behaviours known to be illegal (and therefore never found in practice) into a single "Mischievous Actor" custom type (like the Puppet actor is another custom type for testing).

**Comment by anorth** [comment]
Yes, I think the Puppet Actor or something like it is the best approach.

**Comment by nonsense** [comment]
@anorth either I have written broken tests, or our assumptions are wrong:

An actor aborting with exitcode in `[1..15] U { negative_number }` results in the VM propagating the given exitcode.
An actor aborting with exitcode 0 results in an unexpected error.

I marked you on the PR just in case.

**Comment by anorth** [comment]
😱 . Don't assume the implementation is correct!
