### ISSUE TITLE
coverage analysis for test vector corpus

### ISSUE THREAD

**Issue by raulk** [filecoin-project/test-vectors#22]
During a call yesterday, @alanshaw asked how we can can identify which areas are untested by our test vectors (spoiler alert: many!)

Ideally we'd be able to trace how much of the reference implementation's codebase (Lotus+specs-actors) is exercised via our test vector generation scripts/corpus, so we can easily identify which test vectors need to be written to capture untested areas.

* We can use go cover profiles for this, targeting the Lotus VM package and all of specs-actors for the cover profile.
* We could hook in Coveralls or Codecov to give us a live new.

Note that our coverage analysis will overlap with the cover analysis of [specs-actors] tests (https://codecov.io/gh/filecoin-project/specs-actors), but the context is different, so I think it's justified.

Ideally we'd be able to measure not just binary yes/no coverage, but also coverage density, so that we know how many times a particular line/path has been hit.

## Actions

Experiment.

- [ ] Try to set up coverage analysis in CI, filtering by the above packages.
- [ ] Visualise in Coveralls or Codecov.

**Comment by willscott** [comment]
Initial notes:
* a standard coveralls / codecov won't work, because we're interested in looking at how much coverage of code in specs-actors we're getting from tests running in lotus - they don't track multi-repo coverage well.

* For `go test -coverpkg ./chain/vm/,github.com/filecoin-project/specs-actors/... -coverprofile=cover.out ./conformance/` which tracks the relevant packages, we currently have 13% line coverage.

* lotus overall has 30% test coverage per its existing reporting https://codecov.io/gh/filecoin-project/lotus

**Comment by anorth** [comment]
I do not think that coverage over specs-actors code should be a goal for you. For the message and tipset level tests, you should rather aim for as little dependence as possible on specs-actors, using the Chaos actor instead for many things.

The actors team will look after test coverage of the actors. The code under test here is an implementation's VM and chain evaluation packages.

**Comment by raulk** [comment]
We have delivered this with the simple golang coverage tooling. Every build on `lotus` generates a CircleCI single-page HTML artifact that displays coverage for the `vm` package and for `specs-actors`.
